version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FLASK_PORT:-5050}:5050"  # Host port mapped to Flask port
    volumes:
      - ./downloads:/downloads  # Persist downloads
    depends_on:
      - redis
    environment:
      - FLASK_PORT=5050
      - YT_DLP_OUTPUT_PATH=/downloads/%(title)s.%(ext)s
      - LOG_FILE=/app/app.log
      - LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery worker --loglevel=info --concurrency=5
    volumes:
      - ./downloads:/downloads
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - YT_DLP_OUTPUT_PATH=/downloads/%(title)s.%(ext)s
