# version: '3.8'

services:
  vdl-app:
    container_name: vdl-app
    hostname: vdl-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FLASK_PORT:-5050}:5050"  # Host port mapped to Flask port
    volumes:
      - ./downloads:/downloads  # Persistant download location local_path:container_path
      - ./logs:/app/logs  # Persistant logs
    depends_on:
      - vdl-redis
    environment:
      - FLASK_PORT=5050
      - YT_DLP_OUTPUT_PATH=/downloads/%(title)s.%(ext)s
      - LOG_FILE=/app/app.log
      - LOG_LEVEL=INFO
      - REDIS_URL=redis://vdl-redis:6379/0

  vdl-redis:
    container_name: vdl-redis
    hostname: vdl-redis
    image: redis:alpine
    ports:
      - "6379:6379"

  vdl-celery-worker:
    container_name: vdl-celery-worker
    hostname: vdl-celery-worker
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery worker --loglevel=info --concurrency=5
    volumes:
      - ./downloads:/downloads
    depends_on:
      - vdl-redis
    environment:
      - REDIS_URL=redis://vdl-redis:6379/0
      - YT_DLP_OUTPUT_PATH=/downloads/%(title)s.%(ext)s
